### ISSUE TITLE
How about providing a providers.tsx in the library?

### ISSUE THREAD

**Issue by in-ch** [NdungutseCharles103/next13-progressbar#3]
Hello. Thank you for the nice library.

I have a question.
I'm not sure why we need to create a separate <code>providers.tsx</code> for each project.
How about providing a <code>providers.tsx</code> in the library?

**Comment by NdungutseCharles103** [comment]
You have to create a separate ```providers.tsx```  because we want you to mark it as client component as it is necessary to the package. You can also mark ```layout.tsx``` as 'use client' component as well. But coming  back to your idea of providing the provider in the package, It is not possible as providing 'use client' in the package won't be recognized in the build time and hence not be recognised in next.js app which will require 'use client' again in the file you imported it. So that's how it should be.

**Comment by in-ch** [comment]
Thank you for answer. 

When I modified the library to provide <code>providers.tsx</code>, the following error occurred.
And like you said, I knew my idea was impossible.

thank you.

![스크린샷 2023-09-06 오후 1 32 56](https://github.com/NdungutseCharles103/next13-progressbar/assets/49556566/9d86b92c-ef70-40a4-9844-979265e325b0)
